(put 'host-init 'rcsid
 "$Id: host-init.el,v 1.1 2005-05-19 20:52:25 cvs Exp $")

(require 'default-frame-configurations)

(tool-bar-mode -1)

(setq default-frame-configurations
      `(
	("laptop"
	 (top . 20)
	 (left . 23)
	 (width . 60)
	 (height . 40)
	 (background-mode . light)
	 (cursor-type . box)
	 (border-color . "black")
	 (cursor-color . "black")
	 (mouse-color . "black")
	 (background-color . "white")
	 (foreground-color . "black")
	 (vertical-scroll-bars)
	 (internal-border-width . 0)
	 (border-width . 2)
	 (font .  "-adobe-helvetica-medium-r-normal--12-120-75-75-p-67-iso10646-1")
	 (menu-bar-lines . 0)
	 )
	("helvetica"
	 (top . 20)
	 (left . 23)
	 (width . 60)
	 (height . 40)
	 (background-mode . light)
	 (cursor-type . box)
	 (border-color . "black")
	 (cursor-color . "black")
	 (mouse-color . "black")
	 (background-color . "white")
	 (foreground-color . "black")
	 (vertical-scroll-bars)
	 (internal-border-width . 0)
	 (border-width . 2)
	 (font .  "-adobe-helvetica-medium-r-normal--14-140-75-75-p-77-iso8859-1")
	 (menu-bar-lines . 0)
	 )
	("lucida"
	 (top . 20)
	 (left . 23)
	 (width . 60)
	 (height . 40)
	 (background-mode . light)
	 (cursor-type . box)
	 (border-color . "black")
	 (cursor-color . "black")
	 (mouse-color . "black")
	 (background-color . "white")
	 (foreground-color . "black")
	 (vertical-scroll-bars)
	 (internal-border-width . 0)
	 (border-width . 2)
	 (font . 
	       "-b&h-lucida-medium-r-normal-sans-14-100-100-100-p-80-iso10646-1"
	       )
	 (menu-bar-lines . 0)
	 )
	)
      )

; (default-frame-configuration "laptop")
; (default-frame-configuration "lucida")
(default-frame-configuration "helvetica")

(require 'gnuserv)
(display-time)

