#!/usr/local/bin/perl
#  $Id: find-configs,v 1.10 2005-12-17 05:01:09 tombstone Exp $

use Sys::Hostname;
use POSIX qw(uname);
use Getopt::Long;

GetOptions(
 	   'dir|d=s' => \$dir);

$dir="." unless $dir;

my($hostname)= hostname();
my($sysname, $nodename, $release, $version, $machine) = uname();

# XXX
$sysname="W32" unless ($sysname cmp "Windows NT");

# use bare hostname in case its fully qualified
if (($host,undef,$domain)=($hostname=~ /^(\w+)(\.)(.*)/)) {
    $hostname=$host;
}

# XXX this reflects config.el paths.  should just ask it to tell me, or let emacs compute it.

if (defined $ENV{EMACSPATH}) {
    $emacs= $ENV{EMACSPATH} . "/emacs";
}
else {
    $emacs=`which emacs`;
    chomp $emacs;
}

# this fails under cygwin
# die "you lose ($emacs)" unless (-x $emacs);

$cmd="$emacs --batch --eval \"(message (format \\\"%d.%d\\\" emacs-major-version emacs-minor-version))\"";
$emacscfg=`$cmd 2>&1`;
chomp $emacscfg;
$cmd="find $dir/config -type f -name \"*.el\" -a \\( -path \"*$sysname*\" -o -path \"*/$hostname/*\" -o -path \"*$emacscfg*\" \\)";
map {print} (`$cmd`);



