#!/usr/local/bin/perl
use Sys::Hostname;
use POSIX qw(uname);

my($hostname)= hostname();

my($sysname, $nodename, $release, $version, $machine) = uname();
# XXX
$sysname="W32" unless ($sysname cmp "Windows NT");

$cmd="find ./config -type f -name \"*.el\" -a \\( -path \"*$sysname*\" -o -path \"*$hostname*\" \\)";
map {print} (`$cmd`);



