#!/usr/local/bin/perl
#  $Id: find-configs,v 1.6 2004-08-24 00:37:33 cvs Exp $

use Sys::Hostname;
use POSIX qw(uname);

my($hostname)= hostname();

my($sysname, $nodename, $release, $version, $machine) = uname();
# XXX
$sysname="W32" unless ($sysname cmp "Windows NT");

# XXX this reflects config.el paths.  should just ask it to tell me, or let emacs compute it.

if (defined $ENV{EMACSPATH}) {
    $emacs= $ENV{EMACSPATH} . "/emacs";
}
else {
    $emacs=`which emacs`;
}


# die "you lose" unless (-x $emacs);

$cmd="$emacs --batch --eval \"(message (format \\\"%d.%d\\\" emacs-major-version emacs-minor-version))\"";
$emacscfg=`$cmd 2>&1`;
chomp $emacscfg;
$cmd="find ./config -type f -name \"*.el\" -a \\( -path \"*$sysname*\" -o -path \"*/$hostname/*\" -o -path \"*$emacscfg*\" \\)";
map {print} (`$cmd`);



