#!/usr/local/bin/perl
#      $Id: make-autoloads,v 1.3 2000-09-29 21:16:56 a Exp $

# todo: grab doc strings too
print "(setq autoload-alist `( ";

foreach $fn (@ARGV) {
    foreach $def ("defun", "defmacro") {
	@path=split(?/?, $fn);
	$f=pop(@path);
	open(F, $fn);
	binmode F;
	foreach (<F>) {
	    if (/^\($def/) {
		($pat, $func)=split;
		if ($pat eq "(defmacro") {
		    print "($func \"$f\")\n";
		}
	    }
	    close(F);
	}
    }
}
print "))\n";

print "(mapcar '(lambda (x) (autoload (car x) (cadr x) nil t)) autoload-alist)\n";

