(defun grab-frame-parms ()

  (let ((l (frame-parameters))
	(parms '(font top left width height)))
    (loop for x in parms collect (assoc x l)))
  )

(defun insert-frame-parms ()
  (interactive)
  (insert (pp (grab-frame-parms)))
  nil
  )
; (insert-frame-parms)

; see set-frame-configuration
(defun default-frame-configuration (font)
  (let ((c (assoc font default-frame-configurations)))
    (if c
	(progn
	  (modify-frame-parameters nil (cdr c))
	  (setq default-fontspec (frame-parameter nil 'font))
	  (set-default-font  default-fontspec) ; maybe redundant?
	  )
      (message "no entry for %s found in default-frame-configurations" font )
      )
    )
  )

(setq default-frame-configurations
      `(
	("tahoma"
	 (top . 20)
	 (left . 23)
	 (width . 164)
	 (height . 45)
	 (background-mode . light)
	 (cursor-type . box)
	 (border-color . "black")
	 (cursor-color . "black")
	 (mouse-color . "black")
	 (background-color . "white")
	 (foreground-color . "black")
	 (vertical-scroll-bars)
	 (internal-border-width . 0)
	 (border-width . 2)
	 (font .  "-*-tahoma-normal-r-*-*-16-normal-*-*-*-*-*-*-")
	 (menu-bar-lines . 0)
	 )
	("arial"
	 (top . 20)
	 (left . 23)
	 (width . 150)
	 (height . 44)
	 (background-mode . light)
	 (cursor-type . box)
	 (border-color . "black")
	 (cursor-color . "black")
	 (mouse-color . "black")
	 (background-color . "white")
	 (foreground-color . "black")
	 (vertical-scroll-bars)
	 (internal-border-width . 0)
	 (border-width . 2)
	 (font .  "-outline-arial-normal-r-normal-normal-17-102-120-120-p-80-*-")
	 (menu-bar-lines . 0)
	 )
	("courier new"
	 (top . 20)
	 (left . 23)
	 (width . 121)
	 (height . 41)
	 (background-mode . light)
	 (cursor-type . box)
	 (border-color . "black")
	 (cursor-color . "black")
	 (mouse-color . "black")
	 (background-color . "white")
	 (foreground-color . "black")
	 (vertical-scroll-bars)
	 (internal-border-width . 0)
	 (border-width . 2)
	 (font . "-outline-courier new-normal-r-normal-normal-17-102-120-120-c-100-*-")
	 (menu-bar-lines . 0)
	 )
	)
      )
(provide 'default-frame-configurations)

