(put 'ant-bones 'rcsid
 "$Id$")

(require 'cat-utils)

; tbd compute these ...

(defvar *ant-base-url* "http://ant.apache.org/manual/index.html"  "base url where apache manual is located")

(defvar *ant-things* '(
		       (".NET Tasks" "OptionalTasks/dotnet.html")
		       ("ANTLR" "OptionalTasks/antlr.html")
		       ("AntCall" "CoreTasks/antcall.html")
		       ("AntStructure" "CoreTasks/antstructure.html")
		       ("Antlib namespace" "CoreTypes/antlib.html#antlibnamespace")
		       ("Antlib" "CoreTypes/antlib.html")
		       ("Ant" "CoreTasks/ant.html")
		       ("Apply/ExecOn" "CoreTasks/apply.html")
		       ("Assertions Type" "CoreTypes/assertions.html")
		       ("Attrib" "OptionalTasks/attrib.html")
		       ("Available" "CoreTasks/available.html")
		       ("BUnzip2" "CoreTasks/unpack.html")
		       ("BZip2" "CoreTasks/pack.html")
		       ("Basename" "CoreTasks/basename.html")
		       ("BuildNumber" "CoreTasks/buildnumber.html")
		       ("Built-in Properties" "using.html#built-in-props")
		       ("CVSPass" "CoreTasks/cvspass.html")
		       ("Cab" "OptionalTasks/cab.html")
		       ("Checksum" "CoreTasks/checksum.html")
		       ("Chgrp" "OptionalTasks/chgrp.html")
		       ("Chmod" "CoreTasks/chmod.html")
		       ("Chown" "OptionalTasks/chown.html")
		       ("Class Fileset" "OptionalTypes/classfileset.html")
		       ("Clearcase Tasks" "OptionalTasks/clearcase.html")
		       ("Command Line" "running.html#commandline")
		       ("Command-line Arguments" "using.html#arg")
		       ("Common Attributes" "CoreTasks/common.html")
		       ("Concat" "CoreTasks/concat.html")
		       ("Concepts and Types" "conceptstypeslist.html")
		       ("Conditions" "CoreTypes/custom-programming.html#customconditions")
		       ("Condition" "CoreTasks/condition.html")
		       ("Continuus/Synergy Tasks" "OptionalTasks/ccm.html")
		       ("Copydir" "CoreTasks/copydir.html")
		       ("Copyfile" "CoreTasks/copyfile.html")
		       ("Copy" "CoreTasks/copy.html")
		       ("Core Tasks" "coretasklist.html")
		       ("Current namespace" "CoreTypes/antlib.html#currentnamespace")
		       ("Custom Components" "CoreTypes/custom-programming.html")
		       ("CvsChangeLog" "CoreTasks/changelog.html")
		       ("CvsTagDiff" "CoreTasks/cvstagdiff.html")
		       ("CvsVersion" "CoreTasks/cvsversion.html")
		       ("Cvs" "CoreTasks/cvs.html")
		       ("Cygwin Users" "running.html#cygwin")
		       ("Defaultexcludes" "CoreTasks/defaultexcludes.html")
		       ("Delete" "CoreTasks/delete.html")
		       ("Deltree" "CoreTasks/deltree.html")
		       ("Dependset" "CoreTasks/dependset.html")
		       ("Depend" "OptionalTasks/depend.html")
		       ("Description Type" "CoreTypes/description.html")
		       ("DirSet" "CoreTypes/dirset.html")
		       ("Directory-based Tasks" "dirtasks.html")
		       ("Dirname" "CoreTasks/dirname.html")
		       ("EJB Tasks" "OptionalTasks/ejb.html")
		       ("Ear" "CoreTasks/ear.html")
		       ("Echoproperties" "OptionalTasks/echoproperties.html")
		       ("Echo" "CoreTasks/echo.html")
		       ("Environment Variables" "running.html#envvars")
		       ("Example Buildfile" "using.html#example")
		       ("Exec" "CoreTasks/exec.html")
		       ("Extension Package" "OptionalTypes/extension.html")
		       ("FTP" "OptionalTasks/ftp.html")
		       ("Fail" "CoreTasks/fail.html")
		       ("File Mappers" "CoreTypes/mapper.html")
		       ("FileList" "CoreTypes/filelist.html")
		       ("FileSet" "CoreTypes/fileset.html")
		       ("Files" "running.html#files")
		       ("FilterChains and FilterReaders" "CoreTypes/filterchain.html")
		       ("FilterReaders" "CoreTypes/custom-programming.html#filterreaders")
		       ("FilterSet" "CoreTypes/filterset.html")
		       ("Filter" "CoreTasks/filter.html")
		       ("FixCRLF" "CoreTasks/fixcrlf.html")
		       ("GUnzip" "CoreTasks/unpack.html")
		       ("GZip" "CoreTasks/pack.html")
		       ("GenKey" "CoreTasks/genkey.html")
		       ("Get" "CoreTasks/get.html")
		       ("I/O Redirectors" "CoreTypes/redirector.html")
		       ("IContract" "OptionalTasks/icontract.html")
		       ("Image" "OptionalTasks/image.html")
		       ("Import" "CoreTasks/import.html")
		       ("Input" "CoreTasks/input.html")
		       ("JDepend" "OptionalTasks/jdepend.html")
		       ("JJDoc" "OptionalTasks/jjdoc.html")
		       ("JJTree" "OptionalTasks/jjtree.html")
		       ("JProbe Coverage" "OptionalTasks/jpcoverage.html")
		       ("JUnitReport" "OptionalTasks/junitreport.html")
		       ("JUnit" "OptionalTasks/junit.html")
		       ("Jarlib-available" "OptionalTasks/jarlib-available.html")
		       ("Jarlib-display" "OptionalTasks/jarlib-display.html")
		       ("Jarlib-manifest" "OptionalTasks/jarlib-manifest.html")
		       ("Jarlib-resolve" "OptionalTasks/jarlib-resolve.html")
		       ("Jar" "CoreTasks/jar.html")
		       ("Java System Properties" "running.html#sysprops")
		       ("JavaCC" "OptionalTasks/javacc.html")
		       ("Javac" "CoreTasks/javac.html")
		       ("Javadoc/Javadoc2" "CoreTasks/javadoc.html")
		       ("Javah" "OptionalTasks/javah.html")
		       ("Java" "CoreTasks/java.html")
		       ("Jlink" "OptionalTasks/jlink.html")
		       ("JspC" "OptionalTasks/jspc.html")
		       ("Length" "CoreTasks/length.html")
		       ("Library Dependencies" "install.html#librarydependencies")
		       ("Library Directories" "running.html#libs")
		       ("LoadFile" "CoreTasks/loadfile.html")
		       ("LoadProperties" "CoreTasks/loadproperties.html")
		       ("MParse" "OptionalTasks/mparse.html")
		       ("MacroDef" "CoreTasks/macrodef.html")
		       ("Mail" "CoreTasks/mail.html")
		       ("Manifest" "CoreTasks/manifest.html")
		       ("Metamata Audit" "OptionalTasks/maudit.html")
		       ("Metamata Metrics" "OptionalTasks/mmetrics.html")
		       ("Microsoft Visual SourceSafe Tasks" "OptionalTasks/vss.html#tasks")
		       ("MimeMail" "OptionalTasks/mimemail.html")
		       ("Mkdir" "CoreTasks/mkdir.html")
		       ("Move" "CoreTasks/move.html")
		       ("Namespace Support" "CoreTypes/namespace.html")
		       ("Native2Ascii" "OptionalTasks/native2ascii.html")
		       ("NetRexxC" "OptionalTasks/netrexxc.html")
		       ("Nice" "CoreTasks/nice.html")
		       ("OS/2 Users" "running.html#os2")
		       ("Optional Tasks" "optionaltasklist.html")
		       ("Options" "running.html#options")
		       ("Overview of Ant Tasks" "tasksoverview.html")
		       ("Parallel" "CoreTasks/parallel.html")
		       ("Patch" "CoreTasks/patch.html")
		       ("Path-like Structures" "using.html#path")
		       ("PathConvert" "CoreTasks/pathconvert.html")
		       ("PatternSet" "CoreTypes/patternset.html")
		       ("Perforce Tasks" "OptionalTasks/perforce.html")
		       ("Permissions" "CoreTypes/permissions.html")
		       ("PreSetDef" "CoreTasks/presetdef.html")
		       ("Projects" "using.html#projects")
		       ("Properties" "using.html#properties")
		       ("PropertyFile" "OptionalTasks/propertyfile.html")
		       ("PropertySet" "CoreTypes/propertyset.html")
		       ("Property" "CoreTasks/property.html")
		       ("Pvcs" "OptionalTasks/pvcstask.html")
		       ("RExec" "OptionalTasks/rexec.html")
		       ("Record" "CoreTasks/recorder.html")
		       ("References" "using.html#references")
		       ("Regexp" "CoreTypes/regexp.html")
		       ("RenameExtensions" "OptionalTasks/renameextensions.html")
		       ("Rename" "CoreTasks/rename.html")
		       ("ReplaceRegExp" "OptionalTasks/replaceregexp.html")
		       ("Replace" "CoreTasks/replace.html")
		       ("Rmic" "CoreTasks/rmic.html")
		       ("Rpm" "OptionalTasks/rpm.html")
		       ("Running Ant via Java" "running.html#viajava")
		       ("Scp" "OptionalTasks/scp.html")
		       ("Scriptdef" "OptionalTasks/scriptdef.html")
		       ("Script" "OptionalTasks/script.html")
		       ("Selectors" "CoreTypes/custom-programming.html#customselectors")
		       ("Selectors" "CoreTypes/selectors.html")
		       ("Sequential" "CoreTasks/sequential.html")
		       ("ServerDeploy" "OptionalTasks/serverdeploy.html")
		       ("Set of Extension Packages" "OptionalTypes/extensionset.html")
		       ("Setproxy" "OptionalTasks/setproxy.html")
		       ("SignJar" "CoreTasks/signjar.html")
		       ("Sleep" "CoreTasks/sleep.html")
		       ("Sound" "OptionalTasks/sound.html")
		       ("SourceOffSite" "OptionalTasks/sos.html")
		       ("Splash" "OptionalTasks/splash.html")
		       ("Sql" "CoreTasks/sql.html")
		       ("Sshexec" "OptionalTasks/sshexec.html")
		       ("Starteam Tasks" "OptionalTasks/starteam.html")
		       ("Stylebook" "OptionalTasks/stylebook.html")
		       ("Style" "CoreTasks/style.html")
		       ("Subant" "CoreTasks/subant.html")
		       ("Supported conditions" "CoreTasks/conditions.html")
		       ("Symlink" "OptionalTasks/symlink.html")
		       ("Sync" "CoreTasks/sync.html")
		       ("TStamp" "CoreTasks/tstamp.html")
		       ("Table of Contents" "toc.html")
		       ("Targets" "using.html#targets")
		       ("Tar" "CoreTasks/tar.html")
		       ("Taskdef" "CoreTasks/taskdef.html")
		       ("Tasks" "using.html#tasks")
		       ("Telnet" "OptionalTasks/telnet.html")
		       ("Tempfile" "CoreTasks/tempfile.html")
		       ("Test" "OptionalTasks/test.html")
		       ("Token Filters" "using.html#filters")
		       ("Touch" "CoreTasks/touch.html")
		       ("Translate" "OptionalTasks/translate.html")
		       ("Typedef" "CoreTasks/typedef.html")
		       ("Unjar" "CoreTasks/unzip.html")
		       ("Untar" "CoreTasks/unzip.html")
		       ("Unwar" "CoreTasks/unzip.html")
		       ("Unzip" "CoreTasks/unzip.html")
		       ("Uptodate" "CoreTasks/uptodate.html")
		       ("Visual Age for Java Tasks" "Integration/VAJAntTool.html#tasks")
		       ("Waitfor" "CoreTasks/waitfor.html")
		       ("War" "CoreTasks/war.html")
		       ("Weblogic JSP Compiler" "OptionalTasks/wljspc.html")
		       ("WhichResource" "CoreTasks/whichresource.html")
		       ("Writing a Simple Buildfile" "using.html#buildfile")
		       ("XMLCatalog" "CoreTypes/xmlcatalog.html")
		       ("XmlProperty" "CoreTasks/xmlproperty.html")
		       ("XmlValidate" "OptionalTasks/xmlvalidate.html")
		       ("Xslt" "CoreTasks/style.html")
		       ("ZipFileSet" "CoreTypes/zipfileset.html")
		       ("Zip" "CoreTasks/zip.html")
		       ("build.sysclasspath" "sysclasspath.html")
		       ))

(defun ant-bones (thing)
  (interactive (list (completing-read "help for ant thing: "  *ant-things* nil t)))
  (let ((thing (assoc-ignore-case thing *ant-things*)))
    (w3m-goto-url (concat *ant-base-url* (cadr thing)))
    )
  )

; (assoc-ignore-case "java" *ant-things*)

; (ant-bones "Xslt")
(define-key help-map  "" 'ant-bones)
