(defconst rcs-id "$Id: define.el,v 1.3 2000-07-30 21:07:45 andy Exp $")
(defun define (term) (interactive "sterm: ")
  (perl-command "define" term)
  (pop-to-buffer " *perl*")
  (rename-buffer (format "*define %s" term))
  (beginning-of-buffer)
  )