(defconst rcs-id "$Id: fileness.el,v 1.1 2000-08-07 15:59:31 cvs Exp $")

(defun wordness ()
  (interactive)
  (modify-syntax-entry ?/ "w" (syntax-table))
  (modify-syntax-entry ?_ "w" (syntax-table))
  (modify-syntax-entry ?- "w" (syntax-table))
  (modify-syntax-entry ?. "w" (syntax-table))
  (modify-syntax-entry ?: "w" (syntax-table))
  (modify-syntax-entry ?~ "w" (syntax-table))
  )

(defun fileness ()
  (interactive)
  (modify-syntax-entry ?/ "." (syntax-table))
  (modify-syntax-entry ?_ "." (syntax-table))
  (modify-syntax-entry ?- "." (syntax-table))
  (modify-syntax-entry ?. "." (syntax-table))
  (message "fileness")
  )
