(put 'fileness 'rcsid "$Id: fileness.el,v 1.2 2000-10-03 16:44:06 cvs Exp $")

(defun wordness ()
  (interactive)
  (modify-syntax-entry ?/ "w" (syntax-table))
  (modify-syntax-entry ?_ "w" (syntax-table))
  (modify-syntax-entry ?- "w" (syntax-table))
  (modify-syntax-entry ?. "w" (syntax-table))
  (modify-syntax-entry ?: "w" (syntax-table))
  (modify-syntax-entry ?~ "w" (syntax-table))
  )

(defun fileness ()
  (interactive)
  (modify-syntax-entry ?/ "." (syntax-table))
  (modify-syntax-entry ?_ "." (syntax-table))
  (modify-syntax-entry ?- "." (syntax-table))
  (modify-syntax-entry ?. "." (syntax-table))
  (message "fileness")
  )
