(put 'post-info 'rcsid
 "$Id: post-info.el,v 1.6 2006-06-08 15:22:33 alowe Exp $")

(setq info-files-alist
      '(
	("ada-mode" "ada-mode")
	("as" "as")
	("autosprintf" "autosprintf")
	("autotype" "autotype")
	("bash" "bash")
	("bfd" "bfd")
	("binutils" "binutils")
	("ccmode" "ccmode")
	("cl" "cl")
	("configure" "configure")
	("coreutils" "coreutils")
	("cpp" "cpp")
	("cppinternals" "cppinternals")
	("cygwin-api" "cygwin-api")
	("cygwin-ug-net" "cygwin-ug-net")
	("cygwin" "cygwin")
	("diff" "diff")
	("dir" "dir")
	("dired-x" "dired-x")
	("ebrowse" "ebrowse")
	("ediff" "ediff")
	("efaq" "efaq")
	("elisp" "elisp")
	("emacs" "emacs")
	("emacs-mime" "emacs-mime")
	("eshell" "eshell")
	("eudc" "eudc")
	("find" "find")
	("forms" "forms")
	("gawk" "gawk")
	("gawkinet" "gawkinet")
	("gcc" "gcc")
	("gccinstall" "gccinstall")
	("gccint" "gccint")
	("gdbm" "gdbm")
	("gmp" "gmp")
	("gnus" "gnus")
	("gprof" "gprof")
	("grep" "grep")
	("idlwave" "idlwave")
	("info" "info")
	("info-stnd" "info-stnd")
	("info" "info")
	("ld" "ld")
	("libc" "libc")
	("libm" "libm")
	("message" "message")
	("mh-e" "mh-e")
	("mpfr" "mpfr")
	("pcl-cvs" "pcl-cvs")
	("psgml-api" "psgml-api")
	("psgml" "psgml")
	("reftex" "reftex")
	("sc" "sc")
	("sed" "sed")
	("speedbar" "speedbar")
	("standards" "standards")
	("tar" "tar")
	("texinfo" "texinfo")
	("vip" "vip")
	("viper" "viper")
	("wget" "wget")
	("widget" "widget")
	("woman" "woman")
	))

(defun maninfo (thing)
  (interactive 
   (list (completing-read "info for thing: " info-files-alist)))
  ; todo error checking
  (let ((node (format "(%s)Top" thing)))
    (Info-goto-node node)
    )
  )

(define-key help-map "\C-i" 'maninfo)