(put 'post-diff 'rcsid "$Id: post-diff.el,v 1.2 2000-10-03 16:44:07 cvs Exp $")

(defun diff-recovered-file ()
  (interactive)
  (let ((f (format "/tmp/%s" (gensym))))
    (write-region (point-min) (point-max) f)
    (shell-command (concat "diff " f " " (buffer-file-name)))
    (delete-file f)
    )
  )
