(put 'unix-oblist 'rcsid 
 "$Id$")
;; these are the obarrays for machine sunstar

(defvar shell-obarray (mapcar 'list '(
				      "Cvt"   "Mail" 
				      "Rnmail"   "Uutry"   "X"   "Xs"   "a2p"   "acct" 
				      "acctcms"   "acctcom"   "acctcon"   "acctdisk"   "acctdusg" 
				      "acctmerg"   "acctprc"   "actman"   "adb"   "adduser"   "admin" 
				      "aixterm"   "ali"   "anno"   "answer"   "anytopnm"   "ap" 
				      "applymap"   "ar"   "as"   "at"   "atktopbm"   "audit"   "auditapp" 
				      "auditbin"   "auditpr"   "auditselect"   "auditstream" 
				      "auditwrite"   "autoreply"   "avg4"   "awk"   "backup"   "banner" 
				      "basename"   "batch"   "bc"   "bdiff"   "bellmail"   "bffcreate" 
				      "bfs"   "bggen"   "bibtex"   "biod"   "bioddcfg"   "bos" 
				      "brushtopbm"   "bs"   "burst"   "butc"   "c89"   "cal"   "calendar" 
				      "call"   "callold"   "callup"   "callupold"   "cat"   "cb"   "cc" 
				      "cd"   "cdc"   "cflow"   "checkalias"   "checkcw"   "checkeq" 
				      "checkmm"   "chgrp"   "chkcomp"   "chmod"   "chngstate"   "chown" 
				      "chparm"   "chroot"   "chtcb"   "ci"   "clri"   "cmp"   "cmuwmtopbm" 
				      "co"   "codecenter"   "col"   "comb"   "comm"   "comp"   "compress" 
				      "confer"   "config"   "conflict"   "connect"   "cp"   "cpio"   "cpp" 
				      "craps"   "crash"   "cron"   "crontab"   "crop"   "csh"   "csplit" 
				      "ct"   "ctab"   "ctags"   "cu"   "cubitorle"   "cut"   "cvid"   "cw" 
				      "cxref"   "date"   "dbx"   "dc"   "dcopy"   "dd"   "defkey"   "del" 
				      "delta"   "deroff"   "devices"   "devnm"   "df"   "dfsck"   "diff" 
				      "diff3"   "diffmk"   "dig"   "dircmp"   "dirname"   "diskusg" 
				      "display"   "dist"   "domainname"   "dos"   "dosdel"   "dosdir" 
				      "dosread"   "doswrite"   "dp"   "dsipc"   "dsldxprof"   "dspcat" 
				      "dspmsg"   "dsstate"   "dsxlate"   "du"   "dump"   "dumpfmt" 
				      "dvirle"   "dvitype"   "echo"   "ed"   "edconfig"   "edit" 
				      "eggrep"   "egrep"   "elm"   "emacs"   "enscript"   "env"   "epoch" 
				      "eqn"   "errdead"   "errdemon"   "errpd"   "errpt"   "errstop" 
				      "errupdate"   "ex"   "expr"   "f2p"   "f2ps"   "factor"   "fant" 
				      "faq"   "fastmail"   "fax2tiff"   "ff"   "fgrep"   "file"   "filter" 
				      "find"   "findsrc"   "fitstopgm"   "fmt"   "folder"   "folders" 
				      "format"   "forms"   "fortran"   "forw"   "fptype"   "frm"   "fs" 
				      "fsck"   "fsdb"   "fstopgm"   "fuser"   "fwtmp"   "g3topbm"   "gawk" 
				      "gcc"   "gdev"   "ged"   "gemtopbm"   "gencat"   "gend"   "get" 
				      "get4d"   "getorion"   "getactive"   "getap"   "getbob"   "getcx3d" 
				      "getfb"   "getgmr"   "getiris"   "getmac"   "getmex"   "getopt" 
				      "getqcr"   "getren"   "getsun"   "gettaac"   "gettext"   "getty" 
				      "getx10"   "getx11"   "gftodvi"   "gftopk"   "gftype"   "ggrep" 
				      "giftoppm"   "giftorle"   "gmake"   "gouldtoppm"   "graph" 
				      "graphics"   "graytorle"   "greek"   "grep"   "groups"   "guru" 
				      "gutil"   "h2ph"   "help"   "hipstopgm"   "hp"   "hyphen" 
				      "icontopbm"   "id"   "ident"   "ilbmtoppm"   "imgtoppm"   "inc" 
				      "inews"   "init"   "install"   "install-mh"   "installp" 
				      "internet"   "into"   "ipcrm"   "ipcs"   "ipctable"   "istat" 
				      "join"   "kas"   "keyboard"   "kill"   "killall"   "ksh"   "latex" 
				      "ld"   "less"   "lesskey"   "lex"   "li"   "line"   "link"   "lint" 
				      "lispmtopgm"   "listalias"   "ln"   "locator"   "login"   "loginx" 
				      "logname"   "logout"   "lorder"   "lp"   "ls"   "m4"   "macptopbm" 
				      "mail"   "mailstats"   "make"   "makedbm"   "makekey"   "makekit" 
				      "man"   "mark"   "mc"   "mcut"   "mdrc"   "merge"   "mergechan" 
				      "mesg"   "messages"   "mf"   "mft"   "mgrtopbm"   "mhl"   "mhmail" 
				      "mhpath"   "minidisks"   "mkcatdefs"   "mkdir"   "mkfs"   "mknod" 
				      "mm"   "mmt"   "mmv"   "mount"   "mountd"   "msgchk"   "msh" 
				      "mtvtoppm"   "mv"   "mvdir"   "mwm"   "ncheck"   "ndtable"   "neqn" 
				      "newalias"   "newdf"   "newform"   "newgrp"   "newmail"   "news" 
				      "newsetup"   "newsgroups"   "newt"   "next"   "nfsd"   "nfsstat" 
				      "nice"   "nl"   "nm"   "nntpd"   "nohup"   "nroff"   "od"   "on" 
				      "open"   "orglist"   "pack"   "packf"   "painttorle"   "pal2rgb" 
				      "passwd"   "paste"   "patch"   "pbmlife"   "pbmmake"   "pbmmask" 
				      "pbmpaste"   "pbmreduce"   "pbmtext"   "pbmto10x"   "pbmtoascii" 
				      "pbmtoatk"   "pbmtobbnbg"   "pbmtocmuwm"   "pbmtoepson"   "pbmtog3" 
				      "pbmtogem"   "pbmtogo"   "pbmtoicon"   "pbmtolj"   "pbmtomacp" 
				      "pbmtomgr"   "pbmtopi3"   "pbmtoplot"   "pbmtoptx"   "pbmtorast" 
				      "pbmtox10bm"   "pbmtoxbm"   "pbmtoxwd"   "pbmtoybm"   "pbmtozinc" 
				      "pbmupc"   "pcnfs"   "pcsim"   "pcxtopbm"   "pcxtoppm"   "pdelay" 
				      "pdisable"   "penable"   "perl"   "pg"   "pgmbentley"   "pgmcrater" 
				      "pgmedge"   "pgmenhance"   "pgmhist"   "pgmnorm"   "pgmoil" 
				      "pgmramp"   "pgmtexture"   "pgmtofits"   "pgmtofs"   "pgmtolispm" 
				      "pgmtopbm"   "pgmtoppm"   "pgmtops"   "pgmtorle"   "phold" 
				      "pi1toppm"   "pi3topbm"   "pick"   "picttopbm"   "picttoppm" 
				      "piobe"   "pjtoppm"   "pktogf"   "pktype"   "pltotf"   "pnmarith" 
				      "pnmcat"   "pnmconvol"   "pnmcrop"   "pnmcut"   "pnmdepth" 
				      "pnmenlarge"   "pnmfile"   "pnmflip"   "pnmgamma"   "pnmindex" 
				      "pnminvert"   "pnmmargin"   "pnmnoraw"   "pnmpaste"   "pnmrotate" 
				      "pnmscale"   "pnmshear"   "pnmsmooth"   "pnmtile"   "pnmtops" 
				      "pnmtorast"   "pnmtotiff"   "pnmtoxwd"   "portmap"   "post" 
				      "ppmarith"   "ppmconvol"   "ppmcscale"   "ppmdither"   "ppmforge" 
				      "ppmhist"   "ppmmake"   "ppmpat"   "ppmquant"   "ppmquantall" 
				      "ppmrelief"   "ppmrotate"   "ppmscale"   "ppmshear"   "ppmtoacad" 
				      "ppmtogif"   "ppmtoicr"   "ppmtoilbm"   "ppmtopcx"   "ppmtopgm" 
				      "ppmtopi1"   "ppmtopict"   "ppmtopj"   "ppmtops"   "ppmtopuzz" 
				      "ppmtorast"   "ppmtorgb3"   "ppmtorle"   "ppmtosixel"   "ppmtotga" 
				      "ppmtouil"   "ppmtoxpm"   "ppmtoxwd"   "ppmtoyuv"   "pprint"   "pr" 
				      "prev"   "print"   "printmail"   "prof"   "profiler"   "prompter" 
				      "proto"   "prs"   "ps"   "pshare"   "psidtopgm"   "pstart" 
				      "pstext"   "pts"   "ptx"   "puttext"   "pwck"   "pwd"   "pwtable" 
				      "pyrmask"   "qdaemon"   "qrttoppm"   "qs"   "ras2tiff"   "rastorle" 
				      "rasttopbm"   "rasttopnm"   "rasttoppm"   "rawtopgm"   "rawtoppm" 
				      "rawtorle"   "rc"   "rchgrp"   "rchown"   "rcp"   "rcs"   "rcsclean" 
				      "rcsdiff"   "rcsfreeze"   "rcsintro"   "rcsmerge"   "rcvdist" 
				      "rcvpack"   "rcvstore"   "rcvtty"   "read98721"   "readmsg" 
				      "refile"   "regcmp"   "repl"   "repos"   "restore"   "rexd" 
				      "rgb3toppm"   "rlatorle"   "rleClock"   "rleaddcom"   "rleaddeof" 
				      "rlebg"   "rlebox"   "rlecat"   "rlecomp"   "rledither"   "rleflip" 
				      "rlehdr"   "rlehisto"   "rleldmap"   "rlemandl"   "rlenoise" 
				      "rlepatch"   "rleprint"   "rlequant"   "rlescale"   "rleselect" 
				      "rlesetbg"   "rleskel"   "rlespiff"   "rlesplice"   "rlesplit" 
				      "rlestereo"   "rleswap"   "rletoabA60"   "rletoabA62"   "rletoascii" 
				      "rletogif"   "rletogray"   "rletopaint"   "rletoppm"   "rletops" 
				      "rletorast"   "rletoraw"   "rletorla"   "rletotiff"   "rlezoom" 
				      "rlog"   "rm"   "rmail"   "rmdel"   "rmdir"   "rmf"   "rmm"   "rn" 
				      "rpcgen"   "rpcinfo"   "rsh"   "rstatd"   "runacct"   "runcat" 
				      "rup"   "rusers"   "rusersd"   "rwall"   "rwalld"   "s2p"   "saber" 
				      "sact"   "sadc"   "sag"   "sar"   "sc"   "scan"   "sccsdiff" 
				      "screen"   "sdb"   "sdiff"   "secure"   "sed"   "send"   "sendmail" 
				      "setdma"   "setmnt"   "sh"   "shar"   "shell"   "shlib"   "show" 
				      "showmount"   "shutdown"   "size"   "skulker"   "sldtoppm"   "sleep" 
				      "slitex"   "slocal"   "smush"   "sno"   "sort"   "sortm"   "sound" 
				      "space"   "spctoppm"   "spell"   "spline"   "split"   "splp" 
				      "spost"   "spray"   "sprayd"   "sputoppm"   "stat"   "strip" 
				      "stty"   "su"   "sum"   "sync"   "sysck"   "syslogd"   "tab" 
				      "tabs"   "tail"   "tangle"   "tapechk"   "tar"   "targatorle" 
				      "tbl"   "tc"   "tcsh"   "tctl"   "tee"   "template"   "termdef" 
				      "test"   "tex"   "tftopl"   "tgatoppm"   "tic"   "tiff2bw" 
				      "tiff2ps"   "tiffcmp"   "tiffcp"   "tiffdither"   "tiffdump" 
				      "tiffgt"   "tiffinfo"   "tiffmedian"   "tiffsv"   "tifftopgm" 
				      "tifftopnm"   "tifftorle"   "time"   "timex"   "tlog"   "tlogger" 
				      "to8"   "tobw"   "toc"   "tokmon"   "touch"   "tplot"   "tput" 
				      "tr"   "trace"   "trcrpt"   "trcstop"   "trcupdate"   "trdiag" 
				      "troff"   "true"   "tsh"   "tsort"   "tty"   "tvi"   "ugtable" 
				      "umask"   "umount"   "uname"   "uncompress"   "unexp"   "unget" 
				      "uniq"   "units"   "unlink"   "unmount"   "unshar"   "unslice" 
				      "untab"   "up"   "updatep"   "urt"   "users"   "uss"   "uucheck" 
				      "uucico"   "uucleanup"   "uucp"   "uucpadm"   "uuencodec"   "uukick" 
				      "uulog"   "uuname"   "uupick"   "uusched"   "uustat"   "uuto" 
				      "uutry"   "uux"   "uuxqt"   "uwm"   "val"   "varyoff"   "varyon" 
				      "vc"   "vedit"   "verify"   "vftovp"   "vi"   "view"   "vmh"   "vos" 
				      "vptovf"   "vrm2rtfont"   "vrmconfig"   "wall"   "wasatchrle" 
				      "watch"   "wc"   "weave"   "what"   "whatnow"   "who"   "whom" 
				      "wnewmail"   "write"   "writesrv"   "xargs"   "xbmtopbm"   "xcal" 
				      "xcodecenter"   "xdbx"   "xdf"   "xfig"   "xfonts"   "xgif" 
				      "xgrabsc"   "ximtoppm"   "xlc"   "xlf"   "xloadimage"   "xlock" 
				      "xmafsmon"   "xmconmon"   "xmh"   "xmonui"   "xnlock"   "xping" 
				      "xpm2toppm"   "xpmtoppm"   "xpostit"   "xrn"   "xrnold"   "xroach" 
				      "xsaber"   "xterm"   "xtiff"   "xtokmon"   "xtp"   "xv"   "xvine" 
				      "xwdtopbm"   "xwdtopnm"   "xwdtoppm"   "yacc"   "ybmtopbm" 
				      "ypbind"   "ypcat"   "ypinit"   "ypmatch"   "yppasswd"   "yppasswdd" 
				      "yppoll"   "yppush"   "ypserv"   "ypset"   "ypwhich"   "ypxfr" 
				      "yuvtoppm" )))

;; add section 2 & 3

(setq c-obarray (mapcar 'list '( 
;;  "X"   "names" 
	"AllPlanes"  "BlackPixel"  "WhitePixel"  "ConnectionNumber"  "DefaultColormap" 
		"DefaultDepth"  "XListDepths"  "DefaultGC"  "DefaultRootWindow" 
		"DefaultScreenOfDisplay"  "DefaultScreen"  "DefaultVisual"  "DisplayCells" 
		"DisplayPlanes"  "DisplayString"  "LastKnownRequestProcessed"  "NextRequest" 
		"ProtocolVersion"  "ProtocolRevision"  "QLength"  "RootWindow"  "ScreenCount" 
		"ScreenOfDisplay"  "ServerVendor"  "VendorRelease"  "BlackPixelOfScreen" 
		"WhitePixelOfScreen"  "CellsOfScreen"  "DefaultColormapOfScreen" 
		"DefaultDepthOfScreen"  "DefaultGCOfScreen"  "DefaultVisualOfScreen" 
		"DoesBackingStore"  "DoesSaveUnders"  "DisplayOfScreen" 
		"XScreenNumberOfScreen"  "EventMaskOfScreen"  "HeightOfScreen" 
		"HeightMMOfScreen"  "MaxCmapsOfScreen"  "MinCmapsOfScreen"  "PlanesOfScreen" 
		"RootWindowOfScreen"  "WidthOfScreen"  "WidthMMOfScreen"  "ImageByteOrder" 
		"BitmapBitOrder"  "BitmapPad"  "BitmapUnit"  "DisplayHeight"  "DisplayHeightMM" 
		"DisplayWidth"  "DisplayWidthMM"  "XListPixmapFormats"  "XPixmapFormatValues" 
		"IsCursorKey"  "IsFunctionKey"  "IsKeypadKey"  "IsMiscFunctionKey" 
		"IsModiferKey"  "IsPFKey"  "XAllocClassHint"  "XSetClassHint"  "XGetClassHint" 
		"XClassHint"  "XAllocIconSize"  "XSetIconSizes"  "XGetIconSizes"  "XIconSize" 
		"XAllocStandardColormap"  "XSetRGBColormaps"  "XGetRGBColormaps" 
		"XStandardColormap"  "XAllocSizeHints"  "XSetWMNormalHints" 
		"XGetWMNormalHints"  "XSetWMSizeHints"  "XGetWMSizeHints"  "XSizeHints" 
		"XAllocWMHints"  "XSetWMHints"  "XGetWMHints"  "XWMHints"  "XAddHost" 
		"XAddHosts"  "XListHosts"  "XRemoveHost"  "XRemoveHosts"  "XSetAccessControl" 
		"XEnableAccessControl"  "XDisableAccessControl"  "XHostAddress" 
		"XAllocColor"  "XAllocNamedColor"  "XAllocColorCells"  "XAllocColorPlanes" 
		"XFreeColors"  "XAllowEvents"  "XAnyEvent"  "XEvent"  "XButtonEvent"  "XKeyEvent" 
		"XMotionEvent"  "ButtonRelease"  "XChangeKeyboardControl" 
		"XGetKeyboardControl"  "XAutoRepeatOn"  "XAutoRepeatOff"  "XBell" 
		"XQueryKeymap"  "XKeyboardControl"  "XChangeKeyboardMapping" 
		"XGetKeyboardMapping"  "XDisplayKeycodes"  "XSetModifierMapping" 
		"XGetModifierMapping"  "XNewModifiermap"  "XInsertModifiermapEntry" 
		"XDeleteModifiermapEntry"  "XFreeModifierMap"  "XModifierKeymap" 
		"XClientMessageEvent"  "XChangePointerControl"  "XGetPointerControl" 
		"XChangeSaveSet"  "XAddToSaveSet"  "XRemoveFromSaveSet" 
		"XChangeWindowAttributes"  "XSetWindowBackground" 
		"XSetWindowBackgroundPixmap"  "XSetWindowBorder"  "XSetWindowBorderPixmap" 
		"XCreateWindowEvent"  "XCirculateEvent"  "XCirculateRequestEvent" 
		"XClearArea"  "XClearWindow"  "XColormapEvent"  "XConfigureEvent" 
		"XConfigureRequestEvent"  "XConfigureWindow"  "XMoveWindow"  "XResizeWindow" 
		"XMoveResizeWindow"  "XSetWindowBorderWidth"  "XWindowChanges"  "XCopyArea" 
		"XCopyPlane"  "XCreateColormap"  "XCopyColormapAndFree"  "XFreeColormap" 
		"XSetWindowColormap"  "XColor"  "XCreateFontCursor"  "XCreatePixmapCursor" 
		"XCreateGlyphCursor"  "XCreateGC"  "XCopyGC"  "XChangeGC"  "XGetGCValues" 
		"XFreeGC"  "XGContextFromGC"  "XGCValues"  "XCreateImage"  "XGetPixel" 
		"XPutPixel"  "XSubImage"  "XAddPixel"  "XDestroyImage"  "XCreatePixmap" 
		"XFreePixmap"  "XCreateRegion"  "XSetRegion"  "XDestroyRegion"  "XCreateWindow" 
		"XCreateSimpleWindow"  "XSetWindowAttributes"  "XCrossingEvent" 
		"XDestroyWindowEvent"  "XDefineCursor"  "XUndefineCursor"  "XDestroyWindow" 
		"XDestroySubwindows"  "XDrawArc"  "XDrawArcs"  "XArc"  "XDrawImageString" 
		"XDrawImageString16"  "XDrawLine"  "XDrawLines"  "XDrawSegments"  "XSegment" 
		"XDrawPoint"  "XDrawPoints"  "XPoint"  "XDrawRectangle"  "XDrawRectangles" 
		"XRectangle"  "XDrawString"  "XDrawString16"  "XDrawText"  "XDrawText16" 
		"XTextItem"  "XTextItem16"  "XEmptyRegion"  "XEqualRegion"  "XPointInRegion" 
		"XRectInRegion"  "XErrorEvent"  "XExposeEvent"  "XFocusChangeEvent" 
		"XFillRectangle"  "XFillRectangles"  "XFillPolygon"  "XFillArc"  "XFillArcs" 
		"XFlush"  "XSync"  "XEventsQueued"  "XPending"  "XFree"  "XNoOp" 
		"XGraphicsExposeEvent"  "XNoExposeEvent"  "XGravityEvent"  "XGetDefault" 
		"XResourceManagerString"  "XrmGetResource"  "XrmQGetResource" 
		"XrmQGetSearchList"  "XrmQGetSearchResource"  "XGetVisualInfo" 
		"XMatchVisualInfo"  "XVisualIDFromVisual"  "XVisualInfo" 
		"XGetWindowAttributes"  "XGetGeometry"  "XWindowAttributes" 
		"XGetWindowProperty"  "XListProperties"  "XChangeProperty" 
		"XRotateWindowProperties"  "XDeleteProperty"  "XGrabButton"  "XUngrabButton" 
		"XGrabKey"  "XUngrabKey"  "XGrabKeyboard"  "XUngrabKeyboard"  "XGrabPointer" 
		"XUngrabPointer"  "XChangeActivePointerGrab"  "XGrabServer"  "XUngrabServer" 
		"XIconifyWindow"  "XWithdrawWindow"  "XReconfigureWMWindow"  "XIfEvent" 
		"XCheckIfEvent"  "XPeekIfEvent"  "XrmInitialize"  "XrmParseCommand"  "XrmValue" 
		"XrmOptionKind"  "XrmOptionDescRec"  "XInstallColormap"  "XUninstallColormap" 
		"XListInstalledColormaps"  "XIntersectRegion"  "XUnionRegion" 
		"XUnionRectWithRegion"  "XSubtractRegion"  "XXorRegion"  "XOffsetRegion" 
		"XShrinkRegion"  "XInternAtom"  "XGetAtomName"  "XKeymapEvent"  "XListFonts" 
		"XFreeFontNames"  "XListFontsWithInfo"  "XFreeFontInfo"  "XLoadFont" 
		"XQueryFont"  "XLoadQueryFont"  "XFreeFont"  "XGetFontProperty"  "XUnloadFont" 
		"XCharStruct"  "XFontProp"  "XChar2b"  "XFontStruct"  "XLookupKeysym" 
		"XRefreshKeyboardMapping"  "XLookupString"  "XRebindKeySym" 
		"XrmMergeDatabases"  "XrmGetFileDatabase"  "XrmPutFileDatabase" 
		"XrmGetStringDatabase"  "XrmDestroyDatabase"  "XMapEvent"  "XMappingEvent" 
		"XMapRequestEvent"  "XMapWindow"  "XMapRaised"  "XMapSubwindows"  "XNextEvent" 
		"XPeekEvent"  "XWindowEvent"  "XCheckWindowEvent"  "XMaskEvent" 
		"XCheckMaskEvent"  "XCheckTypedEvent"  "XCheckTypedWindowEvent" 
		"XOpenDisplay"  "XCloseDisplay"  "XPropertyEvent"  "XParseGeometry" 
		"XParseColor"  "XPolygonRegion"  "XClipBox"  "XPutBackEvent"  "XPutImage" 
		"XGetImage"  "XGetSubImage"  "XrmPutResource"  "XrmQPutResource" 
		"XrmPutStringResource"  "XrmQPutStringResource"  "XrmPutLineResource" 
		"XQueryBestSize"  "XQueryBestTile"  "XQueryBestStipple"  "XQueryColor" 
		"XQueryColors"  "XLookupColor"  "XQueryPointer"  "XQueryTree"  "XReparentEvent" 
		"XResizeRequestEvent"  "XRaiseWindow"  "XLowerWindow"  "XCirculateSubwindows" 
		"XCirculateSubwindowsUp"  "XCirculateSubwindowsDown"  "XRestackWindows" 
		"XReadBitmapFile"  "XWriteBitmapFile"  "XCreatePixmapFromBitmapData" 
		"XCreateBitmapFromData"  "XRecolorCursor"  "XFreeCursor"  "XQueryBestCursor" 
		"XReparentWindow"  "XSelectionClearEvent"  "XSaveContext"  "XFindContext" 
		"XDeleteContext"  "XUniqueContext"  "XSelectionEvent"  "XSelectInput" 
		"XStringListToTextProperty"  "XTextPropertyToStringList"  "XFreeStringList" 
		"XTextProperty"  "XSelectionRequestEvent"  "XSetArcMode"  "XSetSubwindowMode" 
		"XSetGraphicsExposure"  "XSetClipOrigin"  "XSetClipMask" 
		"XSetClipRectangles"  "XSetCloseDownMode"  "XKillClient"  "XSetCommand" 
		"XGetCommand"  "XSetErrorHandler"  "XGetErrorText"  "XDisplayName" 
		"XSetIOErrorHandler"  "XGetErrorDatabaseText"  "XSendEvent" 
		"XDisplayMotionBufferSize"  "XGetMotionEvents"  "XTimeCoord"  "XSetFillStyle" 
		"XSetFillRule"  "XSetFont"  "XSetFontPath"  "XGetFontPath"  "XFreeFontPath" 
		"XSetInputFocus"  "XGetInputFocus"  "XSetLineAttribute"  "XSetDashes" 
		"XSetPointerMapping"  "XGetPointerMapping"  "XSetScreenSaver" 
		"XForceScreenSaver"  "XActivateScreenSaver"  "XResetScreenSaver" 
		"XGetScreenSaver"  "XSetSelectionOwner"  "XGetSelectionOwner" 
		"XConvertSelection"  "XSetState"  "XSetFunction"  "XSetPlanemask" 
		"XSetForeground"  "XSetBackground"  "XSetTransientForHint" 
		"XGetTransientForHint"  "XSetTextProperty"  "XGetTextProperty"  "XSetTile" 
		"XSetStipple"  "XSetTSOrigin"  "XSetWMClientMachine"  "XGetWMClientMachine" 
		"XSetWMColormapWindows"  "XGetWMColormapWindows"  "XSetWMIconName" 
		"XGetWMIconName"  "XSetIconName"  "XGetIconName"  "XSetWMName"  "XGetWMName" 
		"XStoreName"  "XFetchName"  "XSetWMProperties"  "XSetWMProtocols" 
		"XGetWMProtocols"  "XStoreBytes"  "XStoreBuffer"  "XFetchBytes"  "XFetchBuffer" 
		"XRotateBuffers"  "XStoreColors"  "XStoreColor"  "XStoreNamedColor" 
		"XStringToKeysym"  "XKeysymToString"  "XKeycodeToKeysym"  "XKeysymToKeycode" 
		"XSynchronize"  "XSetAfterFunction"  "XTextExtents"  "XTextExtents16" 
		"XQueryTextExtents"  "XQueryTextExtents16"  "XTextWidth"  "XTextWidth16" 
		"XTranslateCoordinates"  "XrmUniqueQuark"  "XrmStringToQuark" 
		"XrmQuarkToString"  "XrmStringToQuarkList"  "XrmStringToBindingQuarkList" 
		"XUnmapEvent"  "XUnmapWindow"  "XUnmapSubwindows"  "XVisibilityNotifyEvent" 
		"XWarpPointer" 
;; "Xt"   "names" 
		"XtConvertAndStore"  "XtCallConverter" 
		      "XtDispatchEvent"  "XtCallAcceptFocus"  "XtPeekEvent" 
		      "XtAppPeekEvent"  "XtIsSubclass"  "XtIsObject" 
		      "_XtCheckSubclassFlag"  "_XtIsSubclassOf"  "XtIsManaged" 
		      "XtIsRealized"  "XtIsSensitive"  "XtOwnSelection" 
		      "XtOwnSelectionIncremental"  "XtMakeResizeRequest" 
		      "XtTranslateCoords"  "XtGetKeysymTable"  "XtKeysymToKeycodeList" 
		      "XtStringConversionWarning"  "XtDisplayStringConversionWarning" 
		      "const"  "colorConvertArgs"  "const"  "screenConvertArg" 
		      "colorConvertArgs"  "screenConvertArg"  "XtAppAddConverter" 
		      "XtAddConverter"  "XtSetTypeConverter"  "XtAppSetTypeConverter" 
		      "XtConvert"  "XtDirectConvert"  "XtParseTranslationTable" 
		      "XtParseAcceleratorTable"  "XtOverrideTranslations" 
		      "XtAugmentTranslations"  "XtInstallAccelerators" 
		      "XtInstallAllAccelerators"  "XtUninstallTranslations" 
		      "XtAppAddActions"  "XtAddActions"  "XtAppAddActionHook" 
		      "XtRemoveActionHook"  "XtCallActionProc"  "XtRegisterGrabAction" 
		      "XtSetMultiClickTime"  "XtGetMultiClickTime"  "XtGetActionKeysym" 
		      "XtTranslateKeycode"  "XtTranslateKey"  "XtSetKeyTranslator" 
		      "XtRegisterCaseConverter"  "XtConvertCase"  "XtInsertEventHandler" 
		      "XtInsertRawEventHandler"  "XtAddEventHandler" 
		      "XtRemoveEventHandler"  "XtAddRawEventHandler" 
		      "XtRemoveRawEventHandler"  "XtInsertEventHandler" 
		      "XtInsertRawEventHandler"  "XtBuildEventMask"  "XtAddGrab" 
		      "XtRemoveGrab"  "XtProcessEvent"  "XtAppProcessEvent" 
		      "XtMainLoop"  "XtAppMainLoop"  "XtAddExposureToRegion" 
		      "XtSetKeyboardFocus"  "XtLastTimestampProcessed"  "XtAddTimeOut" 
		      "XtAppAddTimeOut"  "XtRemoveTimeOut"  "XtAddInput" 
		      "XtAppAddInput"  "XtRemoveInput"  "XtNextEvent"  "XtAppNextEvent" 
		      "XtPending"  "XtAppPending"  "XtRealizeWidget"  "XtDestroyWidget" 
		      "XtSetSensitive"  "XtSetMappedWhenManaged"  "XtNameToWidget" 
		      "XtWindowToWidget"  "XtMergeArgLists"  "XtVaCreateArgsList" 
		      "XtDisplay"  "XtDisplayOfObject"  "XtScreen"  "XtScreenOfObject" 
		      "XtWindow"  "XtWindowOfObject"  "XtName"  "XtSuperclass" 
		      "XtClass"  "XtParent"  "XtAddCallback"  "XtRemoveCallback" 
		      "XtAddCallbacks"  "XtRemoveCallbacks"  "XtRemoveAllCallbacks" 
		      "XtCallCallbacks"  "XtCallCallbackList"  "XtHasCallbacks" 
		      "XtMakeGeometryRequest"  "XtQueryGeometry"  "XtCreatePopupShell" 
		      "XtVaCreatePopupShell"  "XtPopup"  "XtPopupSpringLoaded" 
		      "XtCallbackNone"  "XtCallbackNonexclusive"  "XtCallbackExclusive" 
		      "XtPopdown"  "XtCallbackPopdown"  "XtMenuPopupAction" 
		      "XtCreateWidget"  "XtCreateManagedWidget"  "XtVaCreateWidget" 
		      "XtVaCreateManagedWidget"  "XtCreateApplicationShell" 
		      "XtAppCreateShell"  "XtVaAppCreateShell"  "XtToolkitInitialize" 
		      "XtDisplayInitialize"  "XtAppInitialize"  "XtVaAppInitialize" 
		      "XtInitialize"  "XtOpenDisplay"  "XtCreateApplicationContext" 
		      "XtAppSetFallbackResources"  "XtDestroyApplicationContext" 
		      "XtInitializeWidgetClass"  "XtWidgetToApplicationContext" 
		      "XtDisplayToApplicationContext"  "XtDatabase"  "XtCloseDisplay" 
		      "XtCopyFromParent"  "XtCopyDefaultDepth"  "XtCopyDefaultColormap" 
		      "XtCopyAncestorSensitive"  "XtCopyScreen" 
		      "XrmCompileResourceList"  "XtGetApplicationResources" 
		      "XtVaGetApplicationResources"  "XtGetSubresources" 
		      "XtVaGetSubresources"  "XtSetValues"  "XtVaSetValues" 
		      "XtGetValues"  "XtVaGetValues"  "XtSetSubvalues" 
		      "XtVaSetSubvalues"  "XtGetSubvalues"  "XtVaGetSubvalues" 
		      "XtGetResourceList"  "XtGetConstraintResourceList" 
		      "XtAppSetErrorMsgHandler"  "XtSetErrorMsgHandler" 
		      "XtAppSetWarningMsgHandler"  "XtSetWarningMsgHandler" 
		      "XtAppErrorMsg"  "XtErrorMsg"  "XtAppWarningMsg"  "XtWarningMsg" 
		      "XtAppSetErrorHandler"  "XtSetErrorHandler" 
		      "XtAppSetWarningHandler"  "XtSetWarningHandler"  "XtAppError" 
		      "XtError"  "XtAppWarning"  "XtWarning"  "XtAppGetErrorDatabase" 
		      "XtGetErrorDatabase"  "XtAppGetErrorDatabaseText" 
		      "XtGetErrorDatabaseText"  "XtMalloc"  "XtCalloc"  "XtRealloc" 
		      "XtFree"  "XtAddWorkProc"  "XtAppAddWorkProc"  "XtRemoveWorkProc" 
		      "XtGetGC"  "XtDestroyGC"  "XtReleaseGC"  "XtReleaseCacheRef" 
		      "XtCallbackReleaseCacheRef"  "XtCallbackReleaseCacheRefList" 
		      "XtSetWMColormapWindows"  "XtFindFile"  "XtResolvePathname" 
		      "XtDisownSelection"  "XtGetSelectionValue"  "XtGetSelectionValues" 
		      "XtAppSetSelectionTimeout"  "XtSetSelectionTimeout" 
		      "XtAppGetSelectionTimeout"  "XtGetSelectionTimeout" 
		      "XtGetSelectionRequest"  "XtGetSelectionValueIncremental" 
		      "XtGetSelectionValuesIncremental"  "XtGrabKey"  "XtUngrabKey" 
		      "XtGrabKeyboard"  "XtUngrabKeyboard"  "XtGrabButton" 
		      "XtUngrabButton"  "XtGrabPointer"  "XtUngrabPointer" 
		      "XtGetApplicationNameAndClass"  
;;  "pexfn"   "names" 
"pescape"  "pgdp"  "padd_names_set"  "pappl_data" 
		  "panno_text_rel"  "par_all_structs"  "par_struct_nets" 
		  "par_structs"  "pawait_event"  "pbuild_tran_matrix" 
		  "pcell_array"  "pchange_struct_id"  "pchange_struct_id_refs" 
		  "pchange_struct_refs"  "pclose_ar_file"  "pclose_phigs" 
		  "pclose_struct"  "pclose_ws"  "pcompose_matrix" 
		  "pcompose_tran_matrix"  "pcomp_fill_area_set_gnorm" 
		  "pcopy_all_elems_struct"  "pcreate_store"  "pdel_all_structs" 
		  "pdel_all_structs_ar"  "pdel_elem"  "pdel_elem_range" 
		  "pdel_elems_labels"  "pdel_store"  "pdel_struct" 
		  "pdel_struct_net"  "pdel_struct_nets_ar"  "pdel_structs_ar" 
		  "pelem_search"  "pemergency_close_phigs"  "pempty_struct" 
		  "perr_hand"  "perr_log"  "pescape-1"  "pescape-2"  "pescape-4" 
		  "pescape-5"  "pescape-6"  "pescape-7"  "peval_view_map_matrix" 
		  "peval_view_ori_matrix"  "pexec_struct"  "pfill_area" 
		  "pfill_area_set"  "pflush_events"  "pgse"  "pget_choice" 
		  "pget_loc"  "pget_pick"  "pget_string"  "pget_stroke" 
		  "pget_val"  "pincr_spa_search"  "pinit_choice"  "pinit_loc" 
		  "pinit_pick"  "pinit_string"  "pinit_stroke"  "pinit_val" 
		  "Intro"  "intro"  "pinq_all_conf_structs"  "pinq_anno_facs" 
		  "pinq_ar_files"  "pinq_ar_st"  "pinq_choice_st"  "pinq_colr_facs" 
		  "pinq_colr_map_facs"  "pinq_colr_map_method_facs" 
		  "pinq_colr_map_rep"  "pinq_colr_map_method_st"  "pinq_colr_model" 
		  "pinq_colr_model_facs"  "pinq_colr_rep"  "pinq_conf_res" 
		  "pinq_conf_structs_net"  "pinq_cur_elem_content" 
		  "pinq_curv_surf_facs"  "pinq_cur_elem_type_size"  "pinq_gdp" 
		  "pinq_def_choice_data"  "pinq_def_disp_upd_st" 
		  "pinq_def_loc_data"  "pinq_def_pick_data"  "pinq_def_string_data" 
		  "pinq_def_stroke_data"  "pinq_def_val_data"  "pinq_dcue_facs" 
		  "pinq_dcue_rep"  "pinq_direct_colr_model_facs" 
		  "pinq_disp_space_size"  "pinq_disp_upd_st"  "pinq_dyns_structs" 
		  "pinq_dyns_ws_attrs"  "pinq_dyns_ws_attrs_plus"  "pinq_edge_facs" 
		  "pinq_edge_rep"  "pinq_edge_rep_plus"  "pinq_edit_mode" 
		  "pinq_elem_content"  "pinq_elem_ptr"  "pinq_elem_type_size" 
		  "pinq_err_hand_mode"  "pinq_gse_facs"  "pinq_highl_filter" 
		  "pinq_hlhsr_id_facs"  "pinq_hlhsr_mode"  "pinq_hlhsr_mode_facs" 
		  "pinq_in_overf"  "pinq_int_facs"  "pinq_int_facs_plus" 
		  "pinq_int_rep"  "pinq_int_rep_plus"  "pinq_invis_filter" 
		  "pinq_light_src_facs"  "pinq_light_src_rep"  "pinq_list_avail_gdp" 
		  "pinq_list_avail_ws_types"  "pinq_list_colr_inds" 
		  "pinq_list_colr_map_inds"  "pinq_list_dcue_inds" 
		  "pinq_list_edge_inds"  "pinq_list_int_inds" 
		  "pinq_list_light_src_inds"  "pinq_loc_st"  "pinq_list_pat_inds" 
		  "pinq_list_line_inds"  "pinq_list_marker_inds" 
		  "pinq_list_text_inds"  "pinq_list_view_inds" 
		  "pinq_model_clip_facs"  "pinq_more_simult_events" 
		  "pinq_num_avail_in"  "pinq_num_disp_pris"  "pinq_open_struct" 
		  "pinq_paths_ances"  "pinq_paths_descs"  "pinq_pat_facs" 
		  "pinq_pat_rep"  "pinq_pat_rep_plus"  "pinq_phigs_facs" 
		  "pinq_pick_st"  "plabel"  "pinq_line_facs"  "pinq_line_facs_plus" 
		  "pinq_line_rep"  "pinq_line_rep_plus"  "pinq_marker_facs" 
		  "pinq_marker_rep"  "pinq_marker_rep_plus"  "pinq_posted_structs" 
		  "pinq_pred_colr_map_rep"  "pinq_pred_colr_rep" 
		  "pinq_pred_dcue_rep"  "pinq_pred_edge_rep" 
		  "pinq_pred_edge_rep_plus"  "pinq_pred_int_rep" 
		  "pinq_pred_int_rep_plus"  "pinq_pred_light_src_rep" 
		  "pinq_pred_pat_rep"  "pinq_pred_pat_rep_plus" 
		  "pinq_pred_line_rep"  "pinq_pred_line_rep_plus" 
		  "pinq_pred_marker_rep"  "pinq_pred_marker_rep_plus" 
		  "pinq_pred_text_rep"  "pinq_pred_text_rep_plus" 
		  "pinq_pred_view_rep"  "pinq_rendering_colr_model_facs" 
		  "pinq_set_open_ws"  "pinq_wss_posted"  "pinq_string_st" 
		  "pinq_stroke_st"  "protate"  "pinq_struct_ids"  "pinq_struct_st" 
		  "pinq_struct_status"  "pinq_sys_st"  "pinq_text_extent" 
		  "pinq_text_facs"  "pinq_text_rep"  "pinq_text_rep_plus" 
		  "pinq_val_st"  "pinq_view_facs"  "pinq_view_rep"  "pinq_ws_cat" 
		  "pinq_ws_class"  "pinq_ws_conn_type"  "pinq_ws_st_table" 
		  "pinq_ws_st_table_plus"  "pinq_ws_st"  "pinq_ws_tran"  "pmessage" 
		  "pnuni_bsp_curv"  "pnuni_bsp_surf"  "poffset_elem_ptr" 
		  "popen_ar_file"  "popen_phigs"  "popen_struct"  "popen_ws" 
		  "popen_xphigs"  "ppolyline"  "ppolymarker"  "ppost_struct" 
		  "predraw_all_structs"  "premove_names_set"  "preq_choice" 
		  "preq_loc"  "preq_pick"  "preq_string"  "preq_stroke" 
		  "preq_val"  "prestore_model_clip_vol"  "pret_all_structs" 
		  "pret_paths_ances"  "pret_paths_descs"  "pret_struct_ids" 
		  "pret_struct_nets"  "pret_structs"  "protate_x"  "protate_y" 
		  "protate_z"  "psample_choice"  "psample_loc"  "psample_pick" 
		  "psample_string"  "psample_stroke"  "psample_val"  "pscale" 
		  "pset_anno_style"  "pset_anno_align"  "pset_anno_char_ht" 
		  "pset_anno_char_up_vec"  "pset_anno_path"  "pset_back_int_colr" 
		  "pset_back_refl_eqn"  "pset_back_int_shade_meth" 
		  "pset_back_int_style"  "pset_back_int_style_ind" 
		  "pset_back_refl_props"  "pset_char_expan"  "pset_char_ht" 
		  "pset_char_space"  "pset_char_up_vec"  "pset_choice_mode" 
		  "pset_colr_map_ind"  "pset_colr_map_rep"  "pset_colr_model" 
		  "pset_colr_rep"  "pset_conf_res"  "pset_curve_approx" 
		  "pset_dcue_ind"  "pset_dcue_rep"  "pset_disp_upd_st" 
		  "pset_edge_colr"  "pset_edge_colr_ind"  "pset_edge_flag" 
		  "pset_edge_ind"  "pset_edge_rep"  "pset_edge_rep_plus" 
		  "pset_edgetype"  "pset_edgewidth"  "pset_edit_mode" 
		  "pset_elem_ptr"  "pset_elem_ptr_label"  "pset_err_hand" 
		  "pset_err_hand_mode"  "pset_face_cull_mode" 
		  "pset_face_disting_mode"  "pset_global_tran"  "pset_highl_filter" 
		  "pset_hlhsr_id"  "pset_hlhsr_mode"  "pset_indiv_asf" 
		  "pset_int_colr"  "pset_int_colr_ind"  "pset_int_ind" 
		  "pset_int_rep"  "pset_int_rep_plus"  "pset_int_shad_meth" 
		  "pset_int_style"  "pset_int_style_ind"  "pset_invis_filter" 
		  "pset_light_src_rep"  "pset_light_src_state"  "pset_linetype" 
		  "pset_linewidth"  "pset_local_tran"  "pset_loc_mode" 
		  "pset_marker_size"  "pset_marker_type"  "pset_model_clip_ind" 
		  "pset_model_clip_vol"  "pset_para_surf_characs" 
		  "pset_pat_ref_point"  "pset_pat_ref_point_vecs"  "pset_pat_rep" 
		  "pset_pat_rep_plus"  "pset_pat_size"  "pset_pick_filter" 
		  "pset_pick_id"  "pset_pick_mode"  "pset_line_colr" 
		  "pset_line_colr_ind"  "pset_line_ind"  "pset_line_rep" 
		  "pset_line_rep_plus"  "pset_line_shad_meth"  "pset_marker_colr" 
		  "pset_marker_colr_ind"  "pset_marker_ind"  "pset_marker_rep" 
		  "pset_marker_rep_plus"  "pset_refl_eqn"  "pset_refl_props" 
		  "pset_rendering_colr_model"  "pset_string_mode" 
		  "pset_stroke_mode"  "pset_surf_approx"  "pset_text_align" 
		  "pset_text_colr"  "pset_text_colr_ind"  "pset_text_font" 
		  "pset_text_ind"  "pset_text_path"  "pset_text_prec" 
		  "pset_text_rep"  "pset_text_rep_plus"  "pset_val_mode" 
		  "pset_view_ind"  "pset_view_rep"  "pset_view_tran_in_pri" 
		  "pset_ws_vp"  "pset_ws_win"  "ptext"  "pupd_ws"  "ptran_point" 
		  "ptranslate"  "punpost_all_structs"  "punpost_struct" 
		  "phigs_ws_type_create"  "phigs_ws_type_destroy" 
		  "phigs_ws_type_get"  "phigs_ws_type_set"  
;;  "glfn"   "names" 
	"RGBcolor"  "RGBmode"  "RGBwritemask" 
		 "addtopup"  "arc"  "arcf"  "backbuffer"  "backface"  "bbox2" 
		 "bgnclosedline"  "bgnline"  "bgnpoint"  "bgnpolygon" 
		 "bgnsurface"  "bgntmesh"  "bgntrim"  "blankscreen"  "blanktime" 
		 "blendfunction"  "blink"  "blkqread"  "callobj"  "charstr" 
		 "chunksize"  "circ"  "circf"  "clear"  "clkoff"  "clkon" 
		 "closeobj"  "cmode"  "cmov"  "color"  "colorf"  "compactify" 
		 "concave"  "cpack"  "crv"  "crvn"  "curorigin"  "cursoff" 
		 "curson"  "curstype"  "curvebasis"  "curveit"  "curveprecision" 
		 "cyclemap"  "czclear"  "defbasis"  "defcursor"  "deflinestyle" 
		 "defpattern"  "defpup"  "defrasterfont"  "delobj"  "deltag" 
		 "depthcue"  "dopup"  "doublebuffer"  "draw"  "drawmode" 
		 "editobj"  "endclosedline"  "endfullscrn"  "endline"  "endpick" 
		 "endpoint"  "endpolygon"  "endselect"  "endsurface"  "endtmesh" 
		 "endtrim"  "font"  "freepup"  "frontbuffer"  "fudge" 
		 "fullscrn"  "gRGBcolor"  "gRGBmask"  "gammaramp"  "gbegin" 
		 "gconfig"  "genobj"  "gentag"  "getbackface"  "getbuffer" 
		 "getbutton"  "getcmmode"  "getcolor"  "getcpos"  "getcursor" 
		 "getdcm"  "getdescender"  "getdev"  "getdisplaymode" 
		 "getdrawmode"  "getfont"  "getgpos"  "getheight"  "getlsrepeat" 
		 "getlstyle"  "getlwidth"  "getmap"  "getmatrix"  "getmcolor" 
		 "getmcolors"  "getmmode"  "getnurbsproperty"  "getopenobj" 
		 "getorigin"  "getpattern"  "getplanes"  "getscrmask"  "getsize" 
		 "getsm"  "getvaluator"  "getviewport"  "getwritemask" 
		 "getzbuffer"  "gexit"  "ginit"  "greset"  "gselect"  "gsync" 
		 "gversion"  "iconsize"  "icontitle"  "initnames"  "isobj" 
		 "isqueued"  "istag"  "keepaspect"  "lRGBrange"  "lampoff" 
		 "lampon"  "lgetdepth"  "linesmooth"  "linewidth"  "lmbind" 
		 "lmcolor"  "lmdef"  "loadXfont"  "loadmatrix"  "loadname" 
		 "logicop"  "lookat"  "lrectread"  "lrectwrite"  "lsetdepth" 
		 "lshaderange"  "lsrepeat"  "makeobj"  "maketag"  "mapcolor" 
		 "mapcolors"  "mapw"  "mapw2"  "maxsize"  "minsize"  "mmode" 
		 "move"  "multimap"  "multmatrix"  "n3f"  "newpup"  "newtag" 
		 "noborder"  "noise"  "noport"  "normal"  "nurbscurve" 
		 "nurbssurface"  "objdelete"  "objinsert"  "objreplace"  "onemap" 
		 "ortho"  "ortho2"  "overlay"  "patch"  "patchbasis" 
		 "patchcurves"  "patchprecision"  "pclos"  "pdr"  "perspective" 
		 "pick"  "picksize"  "pmv"  "pnt"  "pntsmooth"  "polarview" 
		 "polf"  "poly"  "popattributes"  "popmatrix"  "popname" 
		 "popviewport"  "prefposition"  "prefsize"  "pushattributes" 
		 "pushmatrix"  "pushname"  "pushviewport"  "pwlcurve"  "qdevice" 
		 "qenter"  "qread"  "qreset"  "qtest"  "rcrv"  "rcrvn"  "rdr" 
		 "readRGB"  "readpixels"  "readsource"  "rect"  "rectcopy" 
		 "rectf"  "rectread"  "rectwrite"  "rectzoom"  "reshapeviewport" 
		 "ringbell"  "rmv"  "rot"  "rpatch"  "rpdr"  "rpmv"  "sbox" 
		 "sboxf"  "sboxfi"  "sboxfs"  "sboxi"  "sboxs"  "screenspace" 
		 "scrmask"  "setbell"  "setcursor"  "setdblights"  "setlinestyle" 
		 "setmap"  "setnurbsproperty"  "setpattern"  "setpup" 
		 "setvaluator"  "shademodel"  "singlebuffer"  "splf"  "stepunit" 
		 "strwidth"  "subpixel"  "swapbuffers"  "swapinterval" 
		 "swaptmesh"  "swinopen"  "textport"  "tie"  "tpoff"  "tpon" 
		 "underlay"  "unqdevice"  "viewport"  "winclose" 
		 "winconstraints"  "windepth"  "window"  "winget"  "winmove" 
		 "winopen"  "winpop"  "winposition"  "winpush"  "winset" 
		 "wintitle"  "wmpack"  "writeRGB"  "writemask"  "writepixels" 
		 "zbuffer"  "zclear"  "zdraw"  "zfunction"  "zsource" 
		 "zwritemask"  
;;  "gp"   "fn"   "names" 
	"GPOPPH"  "GPCLPH"  "GPOPWS"  "GPCRWS"  "GPCLWS" 
		 "GPRAST"  "GPUPWS"  "GPDF"  "GPMSG"  "GPSDAL"  "GPBKAC" 
		 "GPUPWA"  "GPPL3"  "GPPL2"  "GPPM3"  "GPPM2"  "GPTX3"  "GPTX2" 
		 "GPPG3"  "GPPG2"  "GPINLB"  "GPINAD"  "GPAN2"  "GPAN3" 
		 "GPPXL3"  "GPPXL2"  "GPDPL3"  "GPDPL2"  "GPCR2"  "GPCRA2" 
		 "GPEL2"  "GPEL3"  "GPELA2"  "GPELA3"  "GPANR2"  "GPANR3" 
		 "GPNULL"  "GPPLI"  "GPPMI"  "GPTXI"  "GPEI"  "GPII"  "GPLT" 
		 "GPLWSC"  "GPPLCI"  "GPMT"  "GPMSSC"  "GPPMCI"  "GPTXFO" 
		 "GPTXPR"  "GPCHXP"  "GPCHSP"  "GPTXCI"  "GPCHH"  "GPCHUP" 
		 "GPTXPT"  "GPAHSC"  "GPHLCI"  "GPTXCS"  "GPPLET"  "GPAAL" 
		 "GPAH"  "GPCHPM"  "GPCHUB"  "GPPLCD"  "GPPMCD"  "GPTXCD" 
		 "GPAUP"  "GPAPT"  "GPAS"  "GPHLCD"  "GPIS"  "GPISI"  "GPICI" 
		 "GPEF"  "GPELT"  "GPECI"  "GPESC"  "GPECD"  "GPICD"  "GPTCAC" 
		 "GPPSC"  "GPTXAL"  "GPASF"  "GPVWI"  "GPPLR"  "GPPMR"  "GPTXR" 
		 "GPER"  "GPPAR"  "GPCR"  "GPCML"  "GPIR"  "GPXCR"  "GPCPR" 
		 "GPCSR"  "GPDCR"  "GPHR"  "GPLSR"  "GPLTR"  "GPMTR"  "GPCRC" 
		 "GPDLC"  "GPLNR"  "GPMLX3"  "GPMLX2"  "GPGLX3"  "GPGLX2" 
		 "GPVMT3"  "GPVMT2"  "GPVMP3"  "GPVMP2"  "GPWSX3"  "GPWSX2" 
		 "GPVCH"  "GPXVCH"  "GPXVR"  "GPVP"  "GPVIP"  "GPVOP"  "GPTRL3" 
		 "GPTRL2"  "GPSC3"  "GPSC2"  "GPROTX"  "GPROTY"  "GPROTZ" 
		 "GPROT2"  "GPDFCO"  "GPCMT3"  "GPCMT2"  "GPXF3"  "GPXF2" 
		 "GPPREC"  "GPCVD"  "GPCNRS"  "GPVR"  "GPVPLN"  "GPVUP" 
		 "GPCVMT"  "GPEVM3"  "GPEVM2"  "GPOPST"  "GPCLST"  "GPSSS" 
		 "GPEDMO"  "GPSSTH"  "GPCEDT"  "GPBGTR"  "GPENTR"  "GPBGST" 
		 "GPENST"  "GPEXST"  "GPCOND"  "GPCEXS"  "GPCRET"  "GPTEX3" 
		 "GPTEX2"  "GPPSTS"  "GPPTS"  "GPDLNT"  "GPDLNC"  "GPDSNA" 
		 "GPEP"  "GPOEP"  "GPEPLB"  "GPEPPK"  "GPEPCD"  "GPEPLG" 
		 "GPEPPG"  "GPDLE"  "GPDLST"  "GPDSAR"  "GPDAST"  "GPDASA" 
		 "GPEST"  "GPARW"  "GPASSW"  "GPDRW"  "GPARV"  "GPDRV" 
		 "GPDRAV"  "GPEV"  "GPEAV"  "GPDARW"  "GPADCN"  "GPRCN" 
		 "GPPKID"  "GPPKF"  "GPHLF"  "GPIVF"  "GPINLC"  "GPINSK" 
		 "GPINVL"  "GPINCH"  "GPINPK"  "GPINST"  "GPSMLC"  "GPSMSK" 
		 "GPSMVL"  "GPSMCH"  "GPSMPK"  "GPSMST"  "GPRQLC"  "GPRQSK" 
		 "GPRQVL"  "GPRQCH"  "GPRQPK"  "GPRQST"  "GPSMXP"  "GPRQXP" 
		 "GPLCMO"  "GPSKMO"  "GPVLMO"  "GPCHMO"  "GPPKMO"  "GPSTMO" 
		 "GPIDMO"  "GPGTLC"  "GPGTSK"  "GPGTVL"  "GPGTCH"  "GPGTPK" 
		 "GPGTST"  "GPGTXP"  "GPGTMS"  "GPGWIN"  "GPQSYV"  "GPQWSV" 
		 "GPQSTV"  "GPQEDM"  "GPQWST"  "GPQOPW"  "GPQSEV"  "GPQIQO" 
		 "GPQCEV"  "GPQFAR"  "GPQFCH"  "GPQWTN"  "GPQCS"  "GPQATR" 
		 "GPQTIM"  "GPQASV"  "GPQCNR"  "GPQARF"  "GPQACF"  "GPQADS" 
		 "GPQAGD"  "GPQALI"  "GPQAMF"  "GPQAIF"  "GPQALF"  "GPQAPF" 
		 "GPQAVF"  "GPQALW"  "GPQANV"  "GPQAWC"  "GPQAFC"  "GPQGFC" 
		 "GPQXAF"  "GPQAIS"  "GPQAPS"  "GPQAWD"  "GPQAEF"  "GPQFO" 
		 "GPQAFP"  "GPQWSU"  "GPQCML"  "GPQCVE"  "GPQCVX"  "GPQDV" 
		 "GPQHLF"  "GPQIVF"  "GPQRVE"  "GPQRVX"  "GPQWCT"  "GPQWSX" 
		 "GPQBKS"  "GPQABK"  "GPQAIT"  "GPQCVR"  "GPQRVR"  "GPQCVO" 
		 "GPQRVO"  "GPQRCT"  "GPQMDS"  "GPQWTO"  "GPQAR"  "GPQE" 
		 "GPQEP"  "GPQETS"  "GPQEXS"  "GPQOPS"  "GPQRV"  "GPQSTE" 
		 "GPQSTI"  "GPQVR"  "GPQWSA"  "GPQED"  "GPQEHD"  "GPQRST" 
		 "GPQEDA"  "GPQEHA"  "GPQSTS"  "GPICS"  "GPACFO"  "GPDAFO" 
		 "GPPKAP"  "GPIPKC"  "GPPKSC"  "GPAFDW"  "GPCNC"  "GPDNC" 
		 "GPSHDF"  "GPSYNC"  "GPEHND"  "GPELOG"  "GPQEMS"  "GPEMO" 
		 "GPQEMO"  "GPEXIT"  "GPTRCE"  "GPAWEV"  "GPFLEV"  "GPFWEV" 
		 "GPEVHN"  "GPDLER"  "GPDELB"  "GPDLEG"  "GPNLER"  "GPCPST" 
		 "GPCPER"  "GPMVER"  "GPQCH"  "GPQLC"  "GPQPK"  "GPQSK" 
		 "GPQST"  "GPQVL"  "GPQICS"  "GPQPKA"  "GPQITS"  "GPQCR" 
		 "GPQER"  "GPQIR"  "GPQLR"  "GPQMR"  "GPQPAR"  "GPQTR" 
		 "GPQCCH"  "GPQCID"  "GPQCPR"  "GPQCSR"  "GPQDCR"  "GPQHR" 
		 "GPQLSR"  "GPQLTR"  "GPQMTR"  "GPQXCR"  "GPQXER"  "GPQXIR" 
		 "GPQXLR"  "GPQXMR"  "GPQXTR"  "GPQDDV"  "GPQGDP"  "GPQHD" 
		 "GPQNCN"  "GPQNSP"  "GPQWCV"  "GPQNST"  "GPQIT"  "GPQDIT" 
		 "GPQHMO"  "GPQTMO"  "GPQRCM"  "GPQCQM"  "GPQGSE"  "GPQFBC" 
		 "GPQSPD"  "GPQPDC"  "GPQPKT"  "GPQAAF"  "GPQLNR"  "GPQAMO" 
		 "GPQART"  "GPQWD"  "GPQWC"  "GPQDS"  "GPQNV"  "GPQPLF" 
		 "GPQPMF"  "GPQTXF"  "GPQIF"  "GPQPAF"  "GPQCF"  "GPQGD" 
		 "GPQLW"  "GPQLI"  "GPQVF"  "GPQBK"  "GPQDBK"  "GPQISF" 
		 "GPQPCS"  "GPQEF"  "GPQFP"  "GPQLCF"  "GPQPCR"  "GPQPER" 
		 "GPQPIR"  "GPQPLR"  "GPQPMR"  "GPQPPR"  "GPQPTR"  "GPQDVL" 
		 "GPQDPK"  "GPQDLC"  "GPQDSK"  "GPQDST"  "GPQDCH"  "GPQES" 
		 "GPQAES"  "GPIT"  "GPES"  "GPCRSS"  "GPCRFD"  "GPSPMS" 
		 "GPSBMS"  "GPMSPW"  "GPATR"  "GPDTR"  "GPPW"  "GPNBC3" 
		 "GPNBC2"  "GPPGD3"  "GPPGD2"  "GPINAP"  "GPTMAP"  "GPEXAP" 
		 "GPNBS"  "GPCRIB"  "GPFBM"  "GPFBC"  "GPCAC"  "GPSAC"  "GPPGC" 
		 "GPPHEC"  "GPDCI"  "GPHID"  "GPCHLS"  "GPAID"  "GPZBM" 
		 "GPLSS"  "GPLMO"  "GPCPI"  "GPSPR"  "GPBSPR"  "GPFDMO" 
		 "GPSCI"  "GPSCD"  "GPBICI"  "GPBICD"  "GPBSCI"  "GPBSCD" 
		 "GPDCM"  "GPFLM"  "GPTS3"  "GPPHE"  "GPMG3"  "GPMG2"  "GPLG3" 
		 "GPLG2"  "GPCHL3"  "GPCHL2"  "GPPDMO"  "GPEPD"  "GPCUS" 
		 "GPCUR"  "GPIEC"  "GPCFA2"  "GPTNBS"  "GPLDFO"  "GPDLFO" 
		 "GPXPLR"  "GPXPMR"  "GPXTXR"  "GPXIR"  "GPXER"  "GPGTXC" 
		 "GPQCMM"  "GPQCNC"  "GPQSH"  "GPQNCR"  "GPQSSS"  "GPQDCM" 
		 "GPQSHD"  "GPQIBC"  "GPQIBF"  "GPQPO"  "GPQAI"  "GPQSPL" 
		 "GPQNCS"  "GPQNCC"  "GPQNCE"  "GPQNS"  "GPQLTF"  "GPQMTF" 
		 "GPQHF"  "GPQLSF"  "GPQDCF"  "GPQCPF"  "GPQCSF"  "GPQXCF" 
		 "GPQCDF"  "GPQTDF"  "GPQSDF"  "GPQANF"  "GPQCUF"  "GPQIDF" 
		 "GPQIMF"  "GPQXTX"  "GPDFI"  "GPCAI"  "GPCIM2"  "GPCIM3" 
		 "GPDIM"  "GPFRCT"  "GPWRCT"  "GPRDFB"  "GPTRCT"  "GPTWPO" 
		 "GPTHPO"  "GPRRCT"  "GPQICH"  "GPQIMC"  "GPQIMI"  "GPQIMV" 
		 "GPQIMW"  "GPQIW"  "GPSPH"  "GPCONE"  "GPCSI"  "GPCSRS" 
		 "GPCSIR"  "GPQPAS"  "GPQPDS"  "GPELS"  "GPRSTI"  "GPQISN" 
		 "GPQACS"  "GPQCSN"  "GPQACA"  "GPQCNA"  "GPRAS"  "GPRDS" 
		 "GPISS3"  "GPISS"  "GPRISN"  "GPRNBS"  "GPRTNS"  "GPOPAR" 
		 "GPCLAR"  "GPTST"  "GPTSTN"  "GPTAST"  "GPARST"  "GPARSN" 
		 "GPARAS"  "GPRVST"  "GPRVSN"  "GPRVAS"  "GPDRT"  "GPCRT" 
		 "GPSRT"  "GPCARR"  "GPCVW"  "GPDRVW"  "GPCPVP"  "GPTE" 
		 "GPATS"  "GPDRI2"  )))
