(put 'vs 'rcsid
 "$Id: vs.el,v 1.1 2004-03-27 19:03:09 cvs Exp $")

;; visual studio helpers
; (key-description (read-key-sequence ""))
(setq vskeys
      '(
	("M-7"                  "Activates the Call Stack window")
	("M-8"                  "Activates the Disassembly window")
	("M-6"                  "Activates the Memory window")
	("M-2"                  "Activates the Output window")
	("M-5"                  "Activates the Registers window")
	("M-4"                  "Activates the Variables window")
	("M-3"                  "Activates the Watch window")
	("M-0"                  "Activates the Workspace window")
	("M-F10"                "Applies code changes made to C/C++  source files while debugging")
	("M-F2"                 "Edits or navigates bookmarks")
	("M-F12"                "Queries on the selected object or  current context")
	("F12"                    "Displays a symbol definition")
	("S-F12"              "Displays a symbol reference")
	("C-Num +"             "Displays the next symbol definition or  reference")
	("C-Num *"             "Returns to the location preceding the  last browse operation")
	("C-Num -"             "Displays the previous symbol definition or reference")
	("F7"                     "Builds the project")
	("C-F7"                "Compiles the file")
	("C-F5"                "Executes the program")
	("C-Break"             "Stops the build")
	("Esc"                    "Hides windows or cancels modes")
	("C-M"                 "Detects duplicate mnemonics in the  resource")
	("C-W"                 "Edits the application classes and ties  resources to code")
	("C-Space"             "Completes the current statement")
	("C-Ins"               "Copies the selection to the Clipboard")
	("C-C"                 "Copies the selection to the Clipboard")
	("C-X"                 "Cuts the selection and moves it to the  Clipboard")
	("S-Del"              "Cuts the selection and moves it to the  Clipboard")
	("C-B"                 "Edits breakpoints in the program")
	("M-F9"                 "Edits breakpoints in the program")
	("C-F9"                "Enables or disables a breakpoint")
	("F5"                     "Starts or continues the program")
	("M-F11"                "Switches the memory window to the next  display format")
	("M-S-F11"          "Switches the memory window to the  previous display format")
	("S-F9"               "Performs immediate evaluation of  variables and expressions")
	("C-S-F9"          "Removes all breakpoints")
	("C-S-F5"          "Restarts the program")
	("C-F10"               "Runs the program to the line containing the cursor")
	("C-S-F10"         "Sets the instruction pointer to the  line containing the cursor")
	("M-Num *"              "Displays the source line for the  instruction pointer")
	("F11"                    "Steps into the next statement")
	("S-F11"              "Steps out of the current function")
	("F10"                    "Steps over the next statement")
	("S-F5"               "Stops debugging the program")
	("F9"                     "Inserts or removes a breakpoint")
	("C-F11"               "Switches between the source view and  the disassembly view for this  instruction")
	("Del"                    "Deletes the selection")
	("C-S-G"           "Opens a file based on the selected text")
	("C-O"                 "Opens an existing document")
	("C-P"                 "Prints all or part of the document")
	("C-S"                 "Saves the document")
	("C-F"                 "Finds the specified text")
	("M-F3"                 "Finds the specified text")
	("F3"                     "Finds the next occurrence of the  specified text")
	("S-F3"               "Finds the previous occurrence of the  specified text")
	("C-H"                 "Replaces the specified text with  different text")
	("C-D"                 "Activates the Find tool")
	("C-G"                 "Moves to a specified location")
	("F4"                     "Moves to the line containing the next  error or tag")
	("S-F4"               "Moves to the line containing the  previous error or tag")
	("C-7"                 "Creates a new accelerator table  resource")
	("C-5"                 "Creates a new bitmap resource")
	("C-3"                 "Creates a new cursor resource")
	("C-1"                 "Creates a new dialog box resource")
	("C-4"                 "Creates a new icon resource")
	("C-2"                 "Creates a new menu resource")
	("C-R"                 "Creates a new resource of any type")
	("C-8"                 "Creates or opens the string table  resource")
	("C-6"                 "Creates a toolbar resource")
	("C-9"                 "Creates or opens a version information  resource")
	("C-M-T"             "Brings up the completion list box")
	("C-S-P"           "Plays the quick macro")
	("C-S-R"           "Start recording a temporary, throw-away macro")
	("C-N"                 "Creates a new document, project or  workspace")
	("C-S-Space"       "Provides help with parameters of  functions")
	("C-V"                 "Inserts the Clipboard contents at the  insertion point")
	("S-Ins"              "Inserts the Clipboard contents at the  insertion point")
	("C-M-P"             "Activates the Project selection tool")
	("M-F7"                 "Edits the project build and debug  settings")
	("M-Enter"              "Edits the current selection's  properties")
	("C-Y"                 "Redoes the previously undone action")
	("C-S-Z"           "Redoes the previously undone action")
	("C-A"                 "Selects the entire document")
	("C-T"                 "Provides the syntax for a variable,  function or method selected in the  editor")
	("C-Z"                 "Undoes the last action")
	("M-Backspace"          "Undoes the last action")
	("M-right"        "Forward")
	("M-left"         "Back")
	("M-F6"                 "Toggles the docking feature for the  window on and off")
	("S-Esc"              "Hides the window")
	("F6"                     "Activates the next pane")
	("S-F6"               "Activates the previous pane")
	("C-S-F2"          "Clears all bookmarks in the window")
	("F2"                     "Moves to the line containing the next  bookmark")
	("S-F2"               "Moves to the line containing the  previous bookmark")
	("C-F2"                "Toggles a bookmark for the current line on and off")
	("left"             "Moves the cursor one character to the  left")
	("S-left"       "Extends the selection one character to  the left")
	("right"            "Moves the cursor one character to the  right")
	("S-right"      "Extends the selection one character to  the right")
	("C-K"                 "Finds the next matching preprocessor  condition")
	("C-S-K"           "Extends the selection to the next  matching preprocessor condition")
	("C-J"                 "Finds the previous matching  preprocessor condition")
	("C-S-J"           "Extends the selection to the previous  matching preprocessor condition")
	("S-Backspace"        "Deletes the selection or, if there is  no selection, the character to the left of the cursor")
	("Backspace"              "Deletes the selection or, if there is  no selection, the character to the left of the cursor")
	("C-End"               "Moves to the end of the document")
	("C-S-End"         "Extends the selection to the end of the document")
	("C-Home"              "Moves to the beginning of the file")
	("C-S-Home"        "Extends the selection to the beginning  of the file")
	("Ins"                    "Toggles between inserting and replacing text")
	("C-F3"                "Finds the next occurrence of the  selected text")
	("C-S-F3"          "Finds the previous occurrence of the  selected text")
	("C-E"                 "Finds the matching brace")
	("C-]"                 "Finds the matching brace")
	("C-S-]"           "Extends the selection to the matching  brace")
	("C-S-E"           "Extends the selection to the matching  brace")
	("Home"                   "Moves to either the start of the  current line or the start of the text  on that line")
	("S-Home"             "Extends the selection to either the  start of the current line or the start  of the text on that line")
	("C-L"                 "Deletes the selected lines and puts  them on the Clipboard")
	("C-S-L"           "Deletes the selected line")
	("down"             "Moves the cursor down one line")
	("S-down"       "Extends the selection down one line")
	("End"                    "Moves to the end of the current line")
	("S-End"              "Extends the selection to the end of the current line")
	("M-S-T"            "Swaps current and previous lines")
	("up"               "Moves the cursor up one line")
	("S-up"         "Extends the selection up one line")
	("Page Down"              "Moves the cursor down one page")
	("S-Page Down"        "Extends the selection down one page")
	("Page Up"                "Moves the cursor up one page")
	("S-Page Up"          "Extends the selection up one page")
	("C-I"                 "Starts an incremental search forward")
	("C-S-I"           "Starts an incremental search backward")
	("F8"                     "Starts character selection mode")
	("C-S-F8"          "Selects a columnar block of text")
	("C-F8"                "Selects lines of text")
	("M-F8"                 "Formats the selection using the smart  indent settings")
	("C-U"                 "Makes the selection all lowercase")
	("C-S-U"           "Makes the selection all uppercase")
	("M-S-L"            "Deletes the remainder of the sentence")
	("C-S-8"           "Shows or hides tab characters")
	("S-Application"      "Display Context Menu")
	("M-S-F3"           "Find Next by Context")
	("M-G"                  "Goto Declaration or Definition")
	("M-right"        "Forward")
	("M-left"         "Back")
	("M-O"                  "Open Corresponding .h or .cpp")
	("C-S-V"           "Paste from Multiple Buffers")
	("C-up"          "Scrolls the file contents down one line")
	("C-down"        "Scrolls the file contents up one line")
	("C-Del"               "Deletes a word to the right")
	("C-Backspace"         "Deletes a word to the left")
	("C-left"        "Moves back one word")
	("C-S-left"  "Extends the selection back one word")
	("C-right"       "Moves forward one word")
	("C-S-right" "Extends the selection forward one word")
	("C-S-T"           "Swaps the current and previous words")
	)
      )

(defun vskey (pat) (interactive "spat: ")
  (let ((b (zap-buffer "*vskeys*")))
    (loop for x in vskeys when (string-match pat (cadr x)) 
	  do (insert (car x) "\t" (cadr x) "\n"))
    (pop-to-buffer b)
    (beginning-of-buffer)
    (help-mode)
  )
)

(global-set-key (quote [f10]) (quote vskey))

; (vskeys "bookmark")
